language: java

addons:
  sonarcloud:
    organization: "renatomartinsti-github" # the key of the org you chose at step #3
    token:
      secure: ${SONAR_TOKEN}
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner

jdk:
  - oraclejdk8

script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
